name: Build on Windows x64

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up MSVC
        uses: ilammy/msvc-dev-command@v1
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Compile
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022 Win64" ..
          cmake --build . --config Release --target all
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: connexec-windows-x64
          path: build/Release/connexec.exe
