name: MSBuild
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pack
      run: |
          cd C-net_dev
          g++ -std=c++17 -Wno-narrowing connexec/ai_programing_v1.0.cpp -o connexec.exe
          cp connexec.exe ${GITHUB_WORKSPACE}
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
          name: connexec-windows-x64-exe
          path: connexec.exe
    - uses: actions/upload-artifact@v2
      with:
        name: Upload
        path: build
