name: Build Windows x64 EXE

on:
  push:
    branches:
      - main

jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      - name: Set up MSVC
        uses: actions/setup-msvc@v1
        with:
          msvc-version: '17.0'
      - name: Install MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          packages: mingw-w64-i686-gcc mingw-w64-x86_64-gcc
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build EXE
        run: |
          cd connexec/ai_programing_v1.0.cpp
          g++ -std=c++17 -Wno-narrowing main.cpp -o connexec.exe
          cp connexec.exe ${GITHUB_WORKSPACE}
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: connexec-windows-x64-exe
          path: connexec.exe
