name: Build on Windows x64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Build Environment
        run: |
          mkdir build
          cd build

      - name: Compile
        run: |
          cl /nologo /EHsc /I .. /Fe:main.exe ..\ai_programing_v1.0.cpp

      - name: Run tests
        run: |
          main.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: main.exe
          path: build/main.exe
