name: CI/CD for Connexec

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Connexec
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64
          cmake --build . --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: connexec-windows
          path: ./build/Release/connexec.exe

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download Connexec artifact
        uses: actions/download-artifact@v2
        with:
          name: connexec-windows

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: connexec-windows/*.exe
