# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: set env
      run: go get -u golang.org/x/crypto/ssh
           $GOPATH/src/golang.org/x/crypto
           GO111MODULE=auto CGO_ENABLED=0 GOOS=windows GOARCH=amd64

    - name: Build
      run: go build -o mssh_windows_amd64.exe go_net_dev.go
    
    - name: Release
      uses: actions/upload-artifact@v1
      with: # 将下述可执行文件 release 上去
          name: release_win
          files: |
            mssh_windows_amd64.exe
