name: Build Go Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build Executable
        env:
         GO111MODULE: auto 
         CGO_ENABLED: 0 
         GOOS: windows 
         GOARCH: amd64
        run: go build -o mssh_windows_amd64.exe go_net_dev.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release_win
          path: mssh_windows_amd64.exe
