name: Build Windows x64 EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022
    env:
      GOOS: windows
      GOARCH: amd64
      GO111MODULE: on
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Add crypto and term modules to go.mod
        run: |
          git clone https://github.com/panda-cat/C-net_dev
          cd C-net_dev/src

      - name: Download modules
        run: |
         echo "module github.com/panda-cat/C-net_dev" >> go.mod
         echo "require (
            golang.org/x/crypto v0.17.0
            golang.org/x/term v0.3.0
          )" >> go.mod
         go mod download

      - name: Build EXE
        run: |
          cd src
          go build -o device-manager.exe
