name: Build Windows x64 EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022
    env:
      GOOS: windows
      GOARCH: amd64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Add crypto module to go.mod
        run: |
          echo "module github.com/panda-cat/C-net_dev" >> go.mod
          echo "require golang.org/x/crypto v0.17.0" >> go.mod

      - name: Download crypto module
        run: |
          go mod download

      - name: Build EXE
        run: |
          cd src
          go build -o device-manager.exe
