name: Build Windows x64 EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022
    env:
      GOOS: windows
      GOARCH: amd64
      GO111MODULE: on
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Add crypto and term modules to go.mod
        run: |
          git clone https://github.com/panda-cat/C-net_dev
          cd C-net_dev/src
          go mod init

      - name: Download modules
        run: |
          go mod download

      - name: Build EXE
        run: |
          go build -o device-manager.exe go_net_dev.go
